name: Build

on: [push, pull_request]

jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build binary
      run: |
        docker build -t builder .
        docker run --rm -v ${PWD}:/project builder make
    - uses: actions/upload-artifact@v3
      with:
       name: ufdiine
       path: ufdiine.wuhb
